### ISSUE TITLE
Maquetado Registro

### ISSUE THREAD

**Issue by mpalverca** [ElJeringas/Login-React#2]
maquetado del componente (solo formulario no pagina) Registro igual que el login 
*-usar prefijo de u para nombrar las variables de Usuario ej.
uId
uName
uLastName
uEmail
uPhone
uPassword

**Comment by mpalverca** [comment]
Realiza el mismo formulario de login agregando unos campos extras, también se debe agregar el boleano uTerm para terminado y condiciones, si aún tienes dudas me comunicas por chat para comunicarnos,

**Comment by ElJeringas** [comment]
Falta agregar estilos y unir al login como otra ventana...

**Comment by mpalverca** [comment]
se integro react-router-dom esto servira para posibles rutas mas adelante
